### PR TITLE
DO NOT MERGE: CI reproduction of #204

### PR DESCRIPTION
**Pull request by Brachi**
**Throwaway. Do not merge. Close once the red check is on the record.**

This exists only to make CI actually run the failing test from #204.

#243 fixes the bug and splits the work into test-then-fix, but CI never
runs that first commit: the `pull_request` trigger tests the merge result
of the PR head, and the `push` trigger is scoped to `main` and tags. So
#243's checks are green and the reproduction is only visible by checking
out the commit locally.

This PR's head **is** that commit - the test with no fix - so the checks
here should go red with:

```
AttributeError: 'Action' object has no attribute 'groups'
```

Expected shape of the run:

- **5.2 leg** - red. This is the point.
- **4.2 leg** - green. `action.fcurves` still exists on 4.2, so the bug
  doesn't reproduce there.
- Anything without `--game-dir` - green, since the test skips without game
  data.

Once that's visible, close this and merge #243 instead.

Opened as a draft so it can't be merged by accident.

### CODE REVIEW

**Comment by Brachi** [comment]
The fix landed in #243 (a6f9a49). This branch existed only to show the 5.2 leg going red without it, which it did: 3 errors, `AttributeError: 'Action' object has no attribute 'groups'`. Closing unmerged, as intended.
