### PR TITLE
Initial Blender 4.0+ support

### LINKED ISSUE #76: Blender 4.0 support
At least shader node gropus need to be updated to manage API changes in 4.0:
https://developer.blender.org/docs/release_notes/4.0/python_api/#node-groups

Current behavior:
```
Traceback (most recent call last):
  File "/blender/4.0/scripts/addons/albam/blender_ui/import_panel.py", line 47, in execute
    self._execute(item, context)
  File "/blender/4.0/scripts/addons/albam/blender_ui/import_panel.py", line 54, in _execute
    bl_container = import_function(item, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/blender/4.0/scripts/addons/albam/engines/mtfw/mesh.py", line 266, in build_blender_model
    materials = build_blender_materials(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/blender/4.0/scripts/addons/albam/engines/mtfw/material.py", line 92, in build_blender_materials
    _create_mtfw_shader()
  File "/blender/4.0/scripts/addons/albam/engines/mtfw/material.py", line 553, in _create_mtfw_shader
    shader_group.inputs.new("NodeSocketColor", "Diffuse BM")
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'ShaderNodeTree' object has no attribute 'inputs'
```

### PR DESCRIPTION
**Pull request by Brachi**
Closes #76 
Initial support for Blender 4.0 and above, keeping 3.6 compatibility as well.

Tests will run for bpy version 3.6 and 4.1.

### CODE REVIEW

**Review by HenryOfCarim — APPROVED** [review]
LGTM, worked in 3.6 and 4.1 flawlessly
